// Code generated by protoc-gen-go. DO NOT EDIT.
// source: libs.proto

package csi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type InitPluginRequest struct {
	// Parameters used to initialize the plugin.
	Parameters map[string]string `protobuf:"bytes,1,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *InitPluginRequest) Reset()                    { *m = InitPluginRequest{} }
func (m *InitPluginRequest) String() string            { return proto.CompactTextString(m) }
func (*InitPluginRequest) ProtoMessage()               {}
func (*InitPluginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *InitPluginRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type InitPluginResponse struct {
	// One of the following fields MUST be specified.
	//
	// Types that are valid to be assigned to Reply:
	//	*InitPluginResponse_Result_
	//	*InitPluginResponse_Error
	Reply isInitPluginResponse_Reply `protobuf_oneof:"reply"`
}

func (m *InitPluginResponse) Reset()                    { *m = InitPluginResponse{} }
func (m *InitPluginResponse) String() string            { return proto.CompactTextString(m) }
func (*InitPluginResponse) ProtoMessage()               {}
func (*InitPluginResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type isInitPluginResponse_Reply interface {
	isInitPluginResponse_Reply()
}

type InitPluginResponse_Result_ struct {
	Result *InitPluginResponse_Result `protobuf:"bytes,1,opt,name=result,oneof"`
}
type InitPluginResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,oneof"`
}

func (*InitPluginResponse_Result_) isInitPluginResponse_Reply() {}
func (*InitPluginResponse_Error) isInitPluginResponse_Reply()   {}

func (m *InitPluginResponse) GetReply() isInitPluginResponse_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (m *InitPluginResponse) GetResult() *InitPluginResponse_Result {
	if x, ok := m.GetReply().(*InitPluginResponse_Result_); ok {
		return x.Result
	}
	return nil
}

func (m *InitPluginResponse) GetError() *Error {
	if x, ok := m.GetReply().(*InitPluginResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*InitPluginResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _InitPluginResponse_OneofMarshaler, _InitPluginResponse_OneofUnmarshaler, _InitPluginResponse_OneofSizer, []interface{}{
		(*InitPluginResponse_Result_)(nil),
		(*InitPluginResponse_Error)(nil),
	}
}

func _InitPluginResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*InitPluginResponse)
	// reply
	switch x := m.Reply.(type) {
	case *InitPluginResponse_Result_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Result); err != nil {
			return err
		}
	case *InitPluginResponse_Error:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Error); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("InitPluginResponse.Reply has unexpected type %T", x)
	}
	return nil
}

func _InitPluginResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*InitPluginResponse)
	switch tag {
	case 1: // reply.result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InitPluginResponse_Result)
		err := b.DecodeMessage(msg)
		m.Reply = &InitPluginResponse_Result_{msg}
		return true, err
	case 2: // reply.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Error)
		err := b.DecodeMessage(msg)
		m.Reply = &InitPluginResponse_Error{msg}
		return true, err
	default:
		return false, nil
	}
}

func _InitPluginResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*InitPluginResponse)
	// reply
	switch x := m.Reply.(type) {
	case *InitPluginResponse_Result_:
		s := proto.Size(x.Result)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InitPluginResponse_Error:
		s := proto.Size(x.Error)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InitPluginResponse_Result struct {
}

func (m *InitPluginResponse_Result) Reset()                    { *m = InitPluginResponse_Result{} }
func (m *InitPluginResponse_Result) String() string            { return proto.CompactTextString(m) }
func (*InitPluginResponse_Result) ProtoMessage()               {}
func (*InitPluginResponse_Result) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

func init() {
	proto.RegisterType((*InitPluginRequest)(nil), "csi.InitPluginRequest")
	proto.RegisterType((*InitPluginResponse)(nil), "csi.InitPluginResponse")
	proto.RegisterType((*InitPluginResponse_Result)(nil), "csi.InitPluginResponse.Result")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LibStorage service

type LibStorageClient interface {
	InitPlugin(ctx context.Context, in *InitPluginRequest, opts ...grpc.CallOption) (*InitPluginResponse, error)
}

type libStorageClient struct {
	cc *grpc.ClientConn
}

func NewLibStorageClient(cc *grpc.ClientConn) LibStorageClient {
	return &libStorageClient{cc}
}

func (c *libStorageClient) InitPlugin(ctx context.Context, in *InitPluginRequest, opts ...grpc.CallOption) (*InitPluginResponse, error) {
	out := new(InitPluginResponse)
	err := grpc.Invoke(ctx, "/csi.LibStorage/InitPlugin", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LibStorage service

type LibStorageServer interface {
	InitPlugin(context.Context, *InitPluginRequest) (*InitPluginResponse, error)
}

func RegisterLibStorageServer(s *grpc.Server, srv LibStorageServer) {
	s.RegisterService(&_LibStorage_serviceDesc, srv)
}

func _LibStorage_InitPlugin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitPluginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibStorageServer).InitPlugin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/csi.LibStorage/InitPlugin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibStorageServer).InitPlugin(ctx, req.(*InitPluginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LibStorage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "csi.LibStorage",
	HandlerType: (*LibStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitPlugin",
			Handler:    _LibStorage_InitPlugin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "libs.proto",
}

func init() { proto.RegisterFile("libs.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xb3, 0x0d, 0x89, 0x76, 0x72, 0x50, 0x17, 0xd1, 0x90, 0x83, 0x94, 0x1c, 0xa4, 0xa7,
	0x1c, 0xe2, 0xa5, 0x08, 0x22, 0x08, 0x95, 0x0a, 0x0a, 0x65, 0x7d, 0x82, 0xa4, 0x0c, 0x65, 0x71,
	0xcd, 0xc6, 0xd9, 0x8d, 0x90, 0x07, 0xf0, 0x25, 0x7c, 0x5a, 0xc9, 0xae, 0x68, 0x31, 0xf6, 0xb6,
	0x33, 0xf3, 0x7d, 0xfb, 0x0f, 0x03, 0xa0, 0x64, 0x6d, 0x8a, 0x96, 0xb4, 0xd5, 0x3c, 0xdc, 0x18,
	0x99, 0x4d, 0x37, 0x46, 0xfa, 0x3a, 0xff, 0x64, 0x70, 0xf2, 0xd0, 0x48, 0xbb, 0x56, 0xdd, 0x56,
	0x36, 0x02, 0xdf, 0x3a, 0x34, 0x96, 0xdf, 0x03, 0xb4, 0x15, 0x55, 0xaf, 0x68, 0x91, 0x4c, 0xca,
	0x66, 0xe1, 0x3c, 0x29, 0x2f, 0x8b, 0xc1, 0x1a, 0xb1, 0xc5, 0xfa, 0x07, 0x5c, 0x36, 0x96, 0x7a,
	0xb1, 0x63, 0x66, 0x37, 0x70, 0xf4, 0x67, 0xcc, 0x8f, 0x21, 0x7c, 0xc1, 0x3e, 0x65, 0x33, 0x36,
	0x9f, 0x8a, 0xe1, 0xc9, 0x4f, 0x21, 0x7a, 0xaf, 0x54, 0x87, 0xe9, 0xc4, 0xf5, 0x7c, 0x71, 0x3d,
	0x59, 0xb0, 0xfc, 0x83, 0x01, 0xdf, 0x0d, 0x34, 0xad, 0x6e, 0x0c, 0xf2, 0x05, 0xc4, 0x84, 0xa6,
	0x53, 0xd6, 0xfd, 0x92, 0x94, 0x17, 0xa3, 0xcd, 0x3c, 0x58, 0x08, 0x47, 0xad, 0x02, 0xf1, 0xcd,
	0xf3, 0x1c, 0x22, 0x24, 0xd2, 0xe4, 0xa2, 0x92, 0x12, 0x9c, 0xb8, 0x1c, 0x3a, 0xab, 0x40, 0xf8,
	0x51, 0x76, 0x08, 0xb1, 0xf7, 0xee, 0x0e, 0x20, 0x22, 0x6c, 0x55, 0x5f, 0x3e, 0x01, 0x3c, 0xca,
	0xfa, 0xd9, 0x6a, 0xaa, 0xb6, 0xc8, 0x6f, 0x01, 0x7e, 0xb3, 0xf8, 0xd9, 0xff, 0x67, 0xc9, 0xce,
	0xf7, 0x2c, 0x95, 0x07, 0x75, 0xec, 0x4e, 0x7f, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x3c,
	0x57, 0x01, 0x98, 0x01, 0x00, 0x00,
}
